### Mark Interest
POST {{baseUrl}}/interests/3
Content-Type: application/json

{
  "idMember": 3
}

### Mark Interest
POST {{baseUrl}}/interests/3?call_wanted=true
Content-Type: application/json

{
  "idMember": 3
}