### See all items
GET {{baseUrl}}/items/all_items

### See all offered items
GET {{baseUrl}}/items/all_offered_items

### Offer an item for the first time
POST {{baseUrl}}/items/offer
Authorization: {{token}}
Content-Type: application/json

{
  "itemDescription": "itemDescription",
  "title": "title",
  "photo": "photo",
  "itemType": {
    "itemType": "Décoration"
  },
  "member": {
    "id": 2
  },
  "offerList": [
    {
      "timeSlot": "timeSlot"
    }
  ]
}

### Cancel Offer
PUT {{baseUrl}}/items/cancel/1

### See all items by member id
GET {{baseUrl}}/items/all_items/3
Authorization: {{token}}