### See all items
GET {{baseUrl}}/items/all_items/public
Authorization: {{token}}

### See all offered items
GET {{baseUrl}}/items/all_offered_items
Authorization: {{token}}

### GET one
GET {{baseUrl}}/items/1
Authorization: {{token}}

### Offer an item for the first time
POST {{baseUrl}}/items
Authorization: {{token}}
Content-Type: application/json

{
  "itemDescription": "itemDescription",
  "title": "title",
  "photo": "photo",
  "itemType": {
    "itemType": "Décoration"
  },
  "member": {
    "id": 2
  },
  "offerList": [
    {
      "timeSlot": "timeSlot"
    }
  ]
}

### Cancel Offer
PUT {{baseUrl}}/items/cancel/2
Authorization: {{token}}

### See all items by member id
GET {{baseUrl}}/items/member_items/1
Authorization: {{token}}

###
GET {{baseUrl}}/items/assigned_item/5
Authorization: {{token}}

### Modify Offer
PUT {{baseUrl}}/items/modify
Authorization: {{token}}
Content-Type: application/json

{
  "id": 4,
  "itemDescription": "Pour boire café",
  "itemType": {
    "itemType": "Matériel de cuisine"
  },
  "photo": "Mug",
  "title": "Mug Rose"
}

###
GET {{baseUrl}}/items/count/4/given
Authorization: {{token}}

### See item by its id
GET {{baseUrl}}/items/1
Authorization: {{token}}

### Get Given Items
GET {{baseUrl}}/items/given_items/5
Authorization: {{token}}