### get all
GET {{baseUrl}}/members/list_member
Authorization: {{token}}

### getAll confired member
GET {{baseUrl}}/members/list_registered
Authorization: {{token}}

###get all denied member
GET {{baseUrl}}/members/list_denied
Authorization: {{token}}

### Login with default user credentials
POST {{baseUrl}}/members/login
Content-Type: application/json

{
  "username": "bri ",
  "password": "Rad;293"
}

> {%
  client.global.set("token", response.body.token);
%}

### Confirm registration
PUT {{baseUrl}}/members/confirm/3
Authorization: {{token}}

### Deny member
PUT {{baseUrl}}/members/denies/2
Authorization: {{token}}

### Confirm Admin
PUT {{baseUrl}}/members/confirmAdmin/2
Authorization: {{token}}

### Get All Members unauthorized excected
GET {{baseUrl}}/members/list_member

###
GET {{baseUrl}}/members/is_admin
Authorization: {{token}}
Content-Type: application/json

### Login "registered" user credentials, forbidden expected
POST {{baseUrl}}/members/login
Content-Type: application/json

{
  "username": "bri",
  "password": "Rad;293"
}

### Create One memberDTO
POST {{baseUrl}}/members/register
Content-Type: application/json

{
  "username": "LePirelot",
  "password": "pswdPasOuf",
  "lastName": "Pirlot",
  "firstName": "Antoine"
}

### Register john
POST {{baseUrl}}/members/register
Content-Type: application/json

{
  "username": "Coucoun n",
  "password": "Securitas",
  "lastName": "DuMoulin",
  "firstName": "Michel",
  "address": {
    "street": "Avenue Beau Voisin",
    "buildingNumber": 11,
    "postcode": "1410",
    "commune": "Waterloo"
  }
}
