### get all
GET {{baseUrl}}/members

### Create One member
POST {{baseUrl}}/members
Content-Type: application/json

{
  "username": "LePirelot",
  "password": "pswdPasOuf",
  "lastName": "Pirlot",
  "firstName": "Antoine",
  "actualState": "confirmed",
  "phoneNumber": "0478 85 22 64",
  "admin": false
}

### Login with default user credentials
POST {{baseUrl}}/members/login
Content-Type: application/json

{
  "username": "LePirelot",
  "password": "pswdPasOuf"
}

### Register john
POST {{baseUrl}}/members/register
Content-Type: application/json

{
  "username": "JohnZara00",
  "password": "pswdLOL",
  "lastName": "Lefevre",
  "firstName": "John",
  "actualState": "confirmed",
  "phoneNumber": "0472 99 24 15",
  "admin": false
}