### Get all
GET {{baseUrl}}/ratings/all/5
Authorization: {{token}}

### Evaluate an item
POST {{baseUrl}}/ratings/
Authorization: {{token}}
Content-Type: application/json

{
  "item": {
    "id": 1
  },
  "rating": 4,
  "text": "Super !",
  "member": {
    "id": 1
  }
}