POST {{baseUrl}}/recipients
Authorization: {{token}}
Content-Type: application/json

{
  "item": {
    "id": 1
  },
  "member": {
    "username": "bri"
  }
}

### Set Recipient Unavailable
PUT {{baseUrl}}/recipients/unavailable
Authorization: {{token}}
Content-Type: application/json

{
  "member": {
    "id": 2
  }
}